FROM python:2.7

RUN mkdir -p /app
COPY . /app

WORKDIR /app

RUN \
    apt-get install -y -qq libexpat1-dev gcc libssl-dev libffi-dev && \
    make clean && \
    pip install -r requirements.txt && \
    python setup.py develop

CMD ["autopush"]
