FROM python:2.7

RUN mkdir -p /app
COPY . /app

WORKDIR /app
ENV PATH=$PATH:/root/.cargo/bin

RUN \
    export WITH_RUST=release && \
    apt-get update && \
    apt-get install -y -qq libexpat1-dev gcc libssl-dev libffi-dev && \
    curl https://sh.rustup.rs | sh -s -- -y && \
    make clean && \
    pip install -r requirements.txt && \
    python setup.py develop && \
    cd autopush_rs && \
    cargo clean && \
    rustup self uninstall -y

CMD ["autopush"]
